version: '3'

services:
  postgres-db-pgadmin:
    image: dpage/pgadmin4:4.28
    hostname: postgres-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.no
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8080:80
    networks:
      - backend_network

  postgres-db:
    image: postgres:11.10
    hostname: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/dbdata
    ports:
      - 5433:5432
    networks:
      - backend_network

networks:
  backend_network:
    external: true